### ISSUE TITLE
Add Hopper installer

### ISSUE THREAD

**Issue by theevilbit** [kohnakagawa/cidre-vm#5]
Hi,

Not sure if there is an easy way but it would be good to add Hopper:
https://www.hopperapp.com/

Thanks,
Csaba

**Comment by kohnakagawa** [comment]
Thank you for sending this repuest.

Previously, Hopper Disassembler was removed from Homebrew cask because only demo version is available from the website. But, this seems not true now.
https://github.com/orgs/Homebrew/discussions/5080

I will send pull request to Homebrew cask to add the Hopper. If it is merged, I will update the Brewfile.

**Comment by kohnakagawa** [comment]
[Hopper disassembler can be installed via homebrew cask now.](https://github.com/Homebrew/homebrew-cask/pull/174827) I have already added it to the Brewfile, so I close this issue.
